/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeBlock: typeof import('./src/components/CodeBlock.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTour: typeof import('element-plus/es')['ElTour']
    ElTourStep: typeof import('element-plus/es')['ElTourStep']
    Header: typeof import('./src/components/Header.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    OptionsApi: typeof import('./src/components/OptionsApi.vue')['default']
    RenderDocumentation: typeof import('./src/components/RenderDocumentation.vue')['default']
    RenderHtml: typeof import('./src/components/RenderHtml.vue')['default']
    RenderImg: typeof import('./src/components/RenderImg.vue')['default']
    RenderTip: typeof import('./src/components/RenderTip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    TestComponent: typeof import('./src/components/TestComponent.vue')['default']
    ViButton: typeof import('./src/components/ViButton.vue')['default']
    VscodeStep: typeof import('./src/components/VscodeStep.vue')['default']
    Wave: typeof import('./src/components/Wave.vue')['default']
  }
}
